### PR TITLE
Add wait_until_ready config and check if phiremock server is actually running

### PR DESCRIPTION
**Pull request by barell**
This PR adds:
- new configs: wait_until_ready and wait_until_ready_timeout
- if wait_until_ready is set to true it will use phiremock client reset method to call phiremock server
- if phiremock server does not respond within specified timeout, exception will be thrown
- some updates to README

### CODE REVIEW

**Comment by barell** [comment]
This is to fix issue: https://github.com/mcustiel/phiremock-codeception-extension/issues/47

**Comment by barell** [comment]
Made some further improvements to this PR. It can now use Phiremock Client and fallback to curl request. If both Phiremock client and curl extension are not present and wait_until_ready is set to true it will throw exception.

**Comment by mcustiel** [comment]
@barell  thank you very much for your support to phiremock and sorry for the delay to review/merge your PR.

**Comment by barell** [comment]
Awesome, thanks @mcustiel

**Pull request merged**
